version: 2.1
orbs:
  bridgecrew: bridgecrew/checkov@1.0.5
jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: .
          api-key-variable: 088a7b0c-8b7b-4c78-b0b0-e75de83459dc::RKyPobRh1Snx9+l7wnGqwfoCflY=
          prisma-api-url: https://app0.prismacloud.io/
